"""
Django settings for adcapitalcore project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Load environment variables from .env file (if it exists)
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
_secret_key = os.environ.get('SECRET_KEY', '').strip()
if not DEBUG:
    if not _secret_key or _secret_key.startswith('django-insecure'):
        raise ImproperlyConfigured(
            'SECRET_KEY deve ser definida no ambiente de produção (valor forte, não padrão).'
        )
SECRET_KEY = _secret_key or 'django-insecure-*jzy@g1==oqy@(o+*(+ibbsojas%_7-=*hd7+o6*g!*wmzrcrs'

ALLOWED_HOSTS = [
    'adcapitaligreja.com.br',
    'sistema.adcapitaligreja.com.br',
    'cadastro.adcapitaligreja.com.br',
    'api.adcapitaligreja.com.br',
    'localhost',
    '127.0.0.1',
    '.onrender.com'
]
env_hosts = os.environ.get('ALLOWED_HOSTS', '')
if env_hosts:
    ALLOWED_HOSTS.extend([host.strip() for host in env_hosts.split(',')])

# Adiciona o hostname do Render dinamicamente para evitar 400 Bad Request
render_host = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if render_host and render_host not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(render_host)

# staging | production | development
DJANGO_ENV = os.environ.get('DJANGO_ENV', 'production').strip().lower()


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Bibliotecas
    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    'rest_framework_simplejwt.token_blacklist',
    'cloudinary_storage',
    'cloudinary',

    # Meus Apps
    'membros', 
    'financeiro',
    'agenda',
    'analytics',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # Deve vir primeiro!
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'adcapitalcore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'adcapitalcore.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

def _running_tests():
    return 'pytest' in sys.argv[0] or (
        len(sys.argv) > 1 and sys.argv[1] == 'test' and 'manage.py' in sys.argv[0]
    )


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

if not _running_tests() and 'DATABASE_URL' in os.environ:
    DATABASES['default'] = dj_database_url.config(
        conn_max_age=600, # Reutiliza conexões por 10 min (reduz overhead TCP/SSL no cold start)
        conn_health_checks=True, # Descarta conexões zumbis automaticamente
        ssl_require=True,
    )
    DATABASES['default']['OPTIONS'] = {
        'connect_timeout': 30,
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br' # 'en-us'

TIME_ZONE = 'America/Sao_Paulo' # 'UTC'

USE_I18N = True

USE_TZ = True


# Static and Media Files
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuração Moderna de Armazenamento (Django 6.0+)
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# CORS restrito aos domínios da igreja (+ dev local / Capacitor)
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    'https://adcapitaligreja.com.br',
    'https://www.adcapitaligreja.com.br',
    'https://sistema.adcapitaligreja.com.br',
    'https://cadastro.adcapitaligreja.com.br',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'https://localhost',
    'http://localhost',
]
_extra_cors = os.environ.get('CORS_ALLOWED_ORIGINS', '')
if _extra_cors:
    CORS_ALLOWED_ORIGINS.extend([o.strip() for o in _extra_cors.split(',') if o.strip()])

CORS_ALLOW_METHODS = ['DELETE', 'GET', 'OPTIONS', 'PATCH', 'POST', 'PUT']
CORS_PREFLIGHT_MAX_AGE = 86400

CSRF_TRUSTED_ORIGINS = [
    'https://adcapitaligreja.com.br',
    'https://www.adcapitaligreja.com.br',
    'https://sistema.adcapitaligreja.com.br',
    'https://cadastro.adcapitaligreja.com.br',
    'https://api.adcapitaligreja.com.br',
]

if DJANGO_ENV == 'staging':
    ALLOWED_HOSTS.extend([
        'staging-api.adcapitaligreja.com.br',
        'staging.sistema.adcapitaligreja.com.br',
        'staging.cadastro.adcapitaligreja.com.br',
    ])
    _staging_origins = [
        'https://staging.sistema.adcapitaligreja.com.br',
        'https://staging.cadastro.adcapitaligreja.com.br',
        'https://staging-api.adcapitaligreja.com.br',
    ]
    CORS_ALLOWED_ORIGINS.extend(_staging_origins)
    CSRF_TRUSTED_ORIGINS.extend(_staging_origins)

CRON_SECRET = os.environ.get('CRON_SECRET', '').strip()

# Cache compartilhado (PostgreSQL) — rate limit funciona com vários workers no Render
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'adcapital_django_cache',
    }
}

# Cloudinary Credentials
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET')
}

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '120/hour',
        'user': '2000/hour',
        'login': '10/minute',
        'cadastro': '8/minute',
        'reset_senha': '5/hour',
        'curtidas': '30/hour',
        'portal_verify': '20/minute',
        'membros_busca': '30/minute',
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Igreja AD Capital — API',
    'DESCRIPTION': (
        'API REST do sistema pastoral (membros, financeiro, agenda, analytics). '
        'Autenticação via JWT (`Authorization: Bearer <access>`).'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': r'/api/v1',
    'COMPONENT_SPLIT_REQUEST': True,
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'BearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    },
    'SECURITY': [{'BearerAuth': []}],
    'TAGS': [
        {'name': 'auth', 'description': 'Login JWT, health e ping'},
        {'name': 'membros', 'description': 'Cadastro, portal e administração'},
        {'name': 'financeiro', 'description': 'Transações e categorias'},
        {'name': 'agenda', 'description': 'Eventos e programação'},
        {'name': 'analytics', 'description': 'Dashboard e métricas'},
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
}

if not DEBUG:
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True') == 'True'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', 'True') == 'True'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '[{levelname}] {asctime} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'loggers': {
        'membros': {'handlers': ['console'], 'level': 'INFO'},
        'financeiro': {'handlers': ['console'], 'level': 'INFO'},
        'agenda': {'handlers': ['console'], 'level': 'INFO'},
        'analytics': {'handlers': ['console'], 'level': 'INFO'},
    },
}

# Sentry (opcional — ative com SENTRY_DSN no Render)
_sentry_dsn = os.environ.get('SENTRY_DSN', '').strip()
if _sentry_dsn:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    sentry_sdk.init(
        dsn=_sentry_dsn,
        integrations=[DjangoIntegration()],
        environment=os.environ.get('SENTRY_ENVIRONMENT', DJANGO_ENV),
        traces_sample_rate=float(os.environ.get('SENTRY_TRACES_SAMPLE_RATE', '0.1')),
        send_default_pii=False,
    )

# Email Configuration
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
