[pytest]
DJANGO_SETTINGS_MODULE = adcapitalcore.settings
python_files = test_*.py
python_classes = Test* *Tests
python_functions = test_*
testpaths =
    membros/tests
    financeiro
    agenda/tests
addopts = -q
