# Generated by Django 6.0.2 on 2026-05-19 20:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.CharField(choices=[('SITE', 'Site Público'), ('PORTAL', 'Portal do Membro')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_hash', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Acesso',
                'verbose_name_plural': 'Acessos',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['pagina', 'timestamp'], name='analytics_a_pagina_95661c_idx')],
            },
        ),
    ]
