# Generated by Django 6.0.2 on 2026-03-12 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('funcao', models.CharField(choices=[('MEMBRO', 'Membro'), ('PASTOR', 'Pastor(a)'), ('PRESBITERO', 'Presbítero'), ('DIACONO', 'Diácono/Diaconisa'), ('EVANGELISTA', 'Evangelista'), ('MISSIONARIO', 'Missionário(a)'), ('COOPERADOR', 'Cooperador(a)')], default='MEMBRO', max_length=50)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('LIGADO', 'Ligado'), ('DESLIGADO', 'Desligado')], default='LIGADO', max_length=10)),
                ('logradouro', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(default='Brasília', max_length=100)),
                ('uf', models.CharField(default='DF', max_length=2)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('observacoes', models.TextField(blank=True)),
                ('data_entrada', models.DateField(blank=True, null=True)),
                ('data_saida', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grau', models.CharField(choices=[('PAI_MAE', 'Pai/Mãe'), ('FILHO_A', 'Filho(a)'), ('CONJUGE', 'Cônjuge'), ('IRMAO_A', 'Irmão(ã)'), ('OUTRO', 'Outro')], max_length=20)),
                ('membro_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacionado_a', to='membros.membro')),
                ('membro_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentescos', to='membros.membro')),
            ],
            options={
                'unique_together': {('membro_origem', 'membro_destino')},
            },
        ),
    ]
