# Generated by Django 6.0.2 on 2026-04-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0005_alter_membro_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ativo', models.BooleanField(default=True, verbose_name='Portal Ativo')),
                ('pergunta', models.CharField(default='Qual o seu melhor amigo?', max_length=255, verbose_name='Pergunta de Acesso')),
                ('resposta', models.CharField(default='Jesus', max_length=255, verbose_name='Resposta Correta')),
            ],
            options={
                'verbose_name': 'Configuração do Portal',
                'verbose_name_plural': 'Configurações do Portal',
            },
        ),
    ]
