# Generated by Django 6.0.2 on 2026-04-13 02:33

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0010_alter_membro_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='lgpd_documento',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='membros/lgpd/', verbose_name='Documento LGPD Assinado'),
        ),
    ]
