# Generated by Django 6.0.2 on 2026-04-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0011_alter_membro_lgpd_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='ultimo_post_instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL do Último Post do Instagram'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='youtube_channel_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID do Canal YouTube (UC...)'),
        ),
    ]
