# Generated by Django 6.0.2 on 2026-04-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0012_add_youtube_channel_id_instagram_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='genero',
            field=models.CharField(choices=[('M', 'Varão'), ('F', 'Varoa')], default='M', max_length=10),
        ),
    ]
