# Generated by Django 6.0.2 on 2026-05-05 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0014_migrate_genero_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaoportal',
            options={'verbose_name': 'ConfiguraÃ§Ã£o do Portal', 'verbose_name_plural': 'ConfiguraÃ§Ãµes do Portal'},
        ),
        migrations.AlterModelOptions(
            name='configuracaosite',
            options={'verbose_name': 'ConfiguraÃ§Ã£o do Site', 'verbose_name_plural': 'ConfiguraÃ§Ãµes do Site'},
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='beneficiario',
            field=models.CharField(default='IGREJA EVANGELICA ASSEMBLEIA DE DEUS MINISTERIO NA CAPITAL', max_length=255, verbose_name='BeneficiÃ¡rio'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='endereco_completo',
            field=models.TextField(default='Ch 18 Lt 6/7 Setor de MansÃµes IAPI - GuarÃ¡ 2 - BrasÃ\xadlia - DF - 71.081-245', verbose_name='EndereÃ§o Completo'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='pastor_nome',
            field=models.CharField(default='Pastor ResponsÃ¡vel', max_length=255, verbose_name='Nome do Pastor'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='pastoral_titulo',
            field=models.CharField(default='Uma Palavra de FÃ©', max_length=255, verbose_name='TÃ\xadtulo da Mensagem'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='ultimo_post_instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL do Ã\x9altimo Post do Instagram'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='video_sobre_nos_url',
            field=models.URLField(blank=True, null=True, verbose_name='VÃ\xaddeo Sobre NÃ³s (YouTube URL)'),
        ),
        migrations.AlterField(
            model_name='fotogaleria',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem de ExibiÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='cidade',
            field=models.CharField(default='BrasÃ\xadlia', max_length=100),
        ),
        migrations.AlterField(
            model_name='membro',
            name='estado_civil',
            field=models.CharField(choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUVO', 'ViÃºvo(a)')], default='SOLTEIRO', max_length=20),
        ),
        migrations.AlterField(
            model_name='membro',
            name='genero',
            field=models.CharField(choices=[('M', 'VarÃ£o'), ('F', 'Varoa')], default='M', max_length=10),
        ),
        migrations.AlterField(
            model_name='parentesco',
            name='grau',
            field=models.CharField(choices=[('PAI_MAE', 'Pai/MÃ£e'), ('FILHO_A', 'Filho(a)'), ('CONJUGE', 'CÃ´njuge'), ('IRMAO_A', 'IrmÃ£o(Ã£)'), ('OUTRO', 'Outro')], max_length=20),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('SECRETARIO', 'Secretário(a)'), ('TESOUREIRO', 'Tesoureiro(a)'), ('MEMBRO', 'Membro')], default='MEMBRO', max_length=20)),
                ('membro', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='membros.membro')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
