# Generated by Django 6.0.2 on 2026-05-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0015_alter_configuracaoportal_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaoportal',
            options={'verbose_name': 'Configuração do Portal', 'verbose_name_plural': 'Configurações do Portal'},
        ),
        migrations.AlterModelOptions(
            name='configuracaosite',
            options={'verbose_name': 'Configuração do Site', 'verbose_name_plural': 'Configurações do Site'},
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='curtidas_palavra',
            field=models.PositiveIntegerField(default=0, verbose_name='Curtidas na Palavra Pastoral'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='beneficiario',
            field=models.CharField(default='IGREJA EVANGELICA ASSEMBLEIA DE DEUS MINISTERIO NA CAPITAL', max_length=255, verbose_name='Beneficiário'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='endereco_completo',
            field=models.TextField(default='Ch 18 Lt 6/7 Setor de Mansões IAPI - Guará 2 - Brasília - DF - 71.081-245', verbose_name='Endereço Completo'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='pastor_nome',
            field=models.CharField(default='Pastor Responsável', max_length=255, verbose_name='Nome do Pastor'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='pastoral_titulo',
            field=models.CharField(default='Uma Palavra de Fé', max_length=255, verbose_name='Título da Mensagem'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='ultimo_post_instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL do í\x9altimo Post do Instagram'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='video_sobre_nos_url',
            field=models.URLField(blank=True, null=True, verbose_name='Vídeo Sobre Nós (YouTube URL)'),
        ),
        migrations.AlterField(
            model_name='fotogaleria',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='cidade',
            field=models.CharField(default='Brasília', max_length=100),
        ),
        migrations.AlterField(
            model_name='membro',
            name='estado_civil',
            field=models.CharField(choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUVO', 'Viúvo(a)')], default='SOLTEIRO', max_length=20),
        ),
        migrations.AlterField(
            model_name='membro',
            name='genero',
            field=models.CharField(choices=[('M', 'Varão'), ('F', 'Varoa')], default='M', max_length=10),
        ),
        migrations.AlterField(
            model_name='parentesco',
            name='grau',
            field=models.CharField(choices=[('PAI_MAE', 'Pai/Mãe'), ('FILHO_A', 'Filho(a)'), ('CONJUGE', 'Cônjuge'), ('IRMAO_A', 'Irmão(ã)'), ('OUTRO', 'Outro')], max_length=20),
        ),
    ]
