# Generated by Django 6.0.2 on 2026-05-12 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0016_alter_configuracaoportal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='ano_ultimo_email_aniversario',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano Último Email Aniversário'),
        ),
        migrations.CreateModel(
            name='ComentarioPalavra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Visitante')),
                ('texto', models.TextField(verbose_name='Comentário')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='membros.configuracaosite')),
            ],
            options={
                'verbose_name': 'Comentário da Palavra',
                'verbose_name_plural': 'Comentários da Palavra',
                'ordering': ['-criado_em'],
            },
        ),
    ]
