# Generated by Django 6.0.2 on 2026-05-12 15:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0017_membro_ano_ultimo_email_aniversario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('data_publicacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Publicação')),
                ('autor', models.CharField(default='Pastor', max_length=100, verbose_name='Autor')),
                ('is_ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Devocional',
                'verbose_name_plural': 'Devocionais',
                'ordering': ['-data_publicacao', '-criado_em'],
            },
        ),
    ]
