# Generated by Django 6.0.2 on 2026-05-22 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0018_devocional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devocional',
            name='data_publicacao',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de Publicação'),
        ),
    ]
